### ISSUE TITLE
hint cnv -f juicer: TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by sidiropoulos** [parklab/HiNT#2]
Hi, 

I'm experiencing the following error when I'm running `hint cnv` using a juicer `.hic` file as input, both with my own and the test dataset.

```
$ hint cnv -f juicer -m test.hic --refdir hg19 --bicseq /home/projects/cu_10027/apps/software/BICseq2-seg_v0.7.3 -e MboI -r 50000 -g hg19 -o ./ -n test -p 12
[15:32:05] Argument List:
[15:32:05] Hi-C contact matrix = test.hic
[15:32:05] Hi-C contact matrix format = juicer
[15:32:05] resolution = 50000 kb
[15:32:05] Genome = hg19
[15:32:05] BICseq directory = /home/projects/cu_10027/apps/software/BICseq2-seg_v0.7.3
[15:32:05] Name = test
[15:32:05] Output directory = ./
HiC version:  8
Error finding block data

Traceback (most recent call last):
  File "/home/projects/cu_10027/apps/software/miniconda3/4.5.4/envs/hint/bin/hint", line 201, in <module>
    main()
  File "/home/projects/cu_10027/apps/software/miniconda3/4.5.4/envs/hint/bin/hint", line 194, in main
    cnvrun(argparser)
  File "/home/projects/cu_10027/apps/software/miniconda3/4.5.4/envs/hint/lib/python3.6/site-packages/HiNT/runhint.py", line 79, in cnvrun
    rowSumFilesInfo = getGenomeRowSums(opts.resolution, opts.matrixfile, chromlf, opts.outdir,opts.name)
  File "/home/projects/cu_10027/apps/software/miniconda3/4.5.4/envs/hint/lib/python3.6/site-packages/HiNT/getGenomeRowSumsFromHiC.py", line 69, in getGenomeRowSums
    sumInfo = getSumPerChrom(i, j, hicfile, binsize, chroms, chromInfo, sumInfo)
  File "/home/projects/cu_10027/apps/software/miniconda3/4.5.4/envs/hint/lib/python3.6/site-packages/HiNT/getGenomeRowSumsFromHiC.py", line 20, in getSumPerChrom
    result = straw('NONE', hicfile, str(chr1), str(chr2), 'BP', binsize)
  File "/home/projects/cu_10027/apps/software/miniconda3/4.5.4/envs/hint/lib/python3.6/site-packages/HiNT/straw.py", line 543, in straw
    blockBinCount=list1[0]
TypeError: 'int' object is not subscriptable
```

I installed Hint using miniconda3/4.5.4 and python=3.6
Is there any known workaround? 

Thanks,
Nikos

**Comment by suwangbio** [comment]
Hi Nikos,

(1) Please make sure that the reference directory is the current directory that you run this job, since your input for —refdir is hg19, which equals to ./hg19.
(2) For the resolution, I guess you want to use 50kb, so your input should be 50 but not 50000, the unit is kb in HiNT-cnv. Please refer to our instructions on github. I think this is the reason that caused the error in your case.

Thanks,
Su

**Comment by sidiropoulos** [comment]
Hi Su,

Changing the resolution to 50 did the trick. 
Thanks for the quick response and for a great tool!

Best,
Nikos
