### ISSUE TITLE
tabix.TabixError: Can't open the index file.

### ISSUE THREAD

**Issue by Yousuk-Song** [parklab/HiNT#22]
Hi, I tried to run hint cnv and got these error messages.

open: No such file or directory
Traceback (most recent call last):
  File "/data2/home/song7602/Tools/HiNT/bin/hint", line 202, in <module>
    main()
  File "/data2/home/song7602/Tools/HiNT/bin/hint", line 194, in main
    cnvrun(argparser)
  File "/data2/home/song7602/Tools/HiNT/HiNT/runhint.py", line 86, in cnvrun
    chroms,regressionFileAllchroms,regressionChromFilesInfo = prepareData(opts.name,opts.outdir,opts.referencedir,chromlf,rowSumFilesInfo,binsize,GCPercent_1kb,mappablity_track,restrictionSites) #Prepare the other data Information for regression
  File "/data2/home/song7602/Tools/HiNT/HiNT/prepare_regression.py", line 167, in prepareData
    mapscore = getmappability(mappablity_track, chrom, 1, chromLength, resolution)
  File "/data2/home/song7602/Tools/HiNT/HiNT/prepare_regression.py", line 42, in getmappability
    tb = tabix.open(mappablity_track)
tabix.TabixError: Can't open the index file.

is mappability_track file required as an input for running hint cnv? and if it is, which path should it be located in? at reference genome directory?

**Comment by ozanmujde** [comment]
Hi, the error happens because you probably did not include any mappability file and as I understand after [downloading](https://bismap.hoffmanlab.org/)  I think you should remove the header sorry that I forgot what but It may be this  ```
$ gunzip -c k50.umap.bed.gz | head -n 5
$  gunzip -c k50.umap.bed.gz | grep -v "^track" | awk '{print $1 "\t" $2 "\t" $3 "\t" $5}' > temp.bed
$  bgzip -c temp.bed > hg38_mappability_50mer.bdg.gz
$  tabix -p bed hg38_mappability_50mer.bdg.gz
$  rm temp.bed
```
